module.exports = [
  {"code": "zh", "name": "简体中文", "name-en": "Chinese (Simple)"},
  {"code": "de", "name": "Deutsch", "name-en": "German"},
  {"code": "el", "name": "Ελληνικά", "name-en": "Greek"},
  {"code": "en", "name": "English", "name-en": "English"},
  {"code": "es", "name": "Español", "name-en": "Spanish"},
  {"code": "fa", "name": "فارسی", "name-en": "Persian", "rtl": true},
  {"code": "fi", "name": "Suomi", "name-en": "Finnish"},
  {"code": "fr", "name": "Français", "name-en": "French"},
  {"code": "he", "name": "עברית", "name-en": "Hebrew", "rtl": true},
  {"code": "id", "name": "Bahasa Indonesia", "name-en": "Indonesian"},
  {"code": "it", "name": "Italiano", "name-en": "Italian"},
  {"code": "ja", "name": "日本語", "name-en": "Japanese"},
  {"code": "ko", "name": "한국어", "name-en": "Korean"},
  {"code": "no", "name": "Norsk", "name-en": "Norwegian"},
  {"code": "pt-br", "name": "Português (BR)", "name-en": "Portuguese (Brazil)"},
  {"code": "pt-pt", "name": "Português (PT)", "name-en": "Portuguese (Portugal)"},
  {"code": "ru", "name": "Русский", "name-en": "Russian"},
  {"code": "tr", "name": "Türkçe", "name-en": "Turkish"},
  {"code": "uk", "name": "Українська", "name-en": "Ukrainian"},
  {"code": "zh-tw", "name": "正體中文（台灣）", "name-en": "Chinese Traditional (Taiwan)"},
  {"code": "vi", "name" : "Tiếng Việt", "name-en" : "Vietnamese"}
]
